language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iikkasohova/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true iikkasohova/dockertest npm run test -- --coverage